import { Terminal, Berth, Crane } from './types';

export const INITIAL_TERMINALS: Terminal[] = [
  {
    id: 'term-1',
    code: 'PPT-T1',
    name: 'Pasir Panjang Terminal Phase 1-2',
    location: 'Singapore South Gateway (S 01°16.2\', E 103°46.5\')',
    status: 'Operational',
    totalBerths: 5,
    activeCranes: 6,
    avgUtilization: 78,
    quayLengthMeters: 2400,
    description: 'High-throughput automated container terminal equipped for Mega-Max 24K TEU container carriers.',
    establishedYear: 2015,
  },
  {
    id: 'term-2',
    code: 'KDH-T2',
    name: 'Keppel Deepwater Super-Hub',
    location: 'Deepwater Channel Sector 4 (S 01°15.8\', E 103°49.1\')',
    status: 'High Load',
    totalBerths: 4,
    activeCranes: 4,
    avgUtilization: 92,
    quayLengthMeters: 1850,
    description: 'Specialized deep-draft quay line servicing transshipment corridors and refrigerated cold-chain cargo.',
    establishedYear: 2018,
  },
  {
    id: 'term-3',
    code: 'JIT-T3',
    name: 'Jurong Island Petrochemical & Bulk Terminal',
    location: 'Western Industrial Basin (S 01°17.4\', E 103°42.2\')',
    status: 'Operational',
    totalBerths: 3,
    activeCranes: 2,
    avgUtilization: 54,
    quayLengthMeters: 1200,
    description: 'Heavy industrial multipurpose berths for bulk dry chemicals, minerals, and containerized breakbulk.',
    establishedYear: 2020,
  },
  {
    id: 'term-4',
    code: 'TMT-T4',
    name: 'Tuas Mega Automation Terminal (Phase 1)',
    location: 'Tuas Western Waters (S 01°13.1\', E 103°38.4\')',
    status: 'Maintenance',
    totalBerths: 2,
    activeCranes: 2,
    avgUtilization: 41,
    quayLengthMeters: 950,
    description: 'Next-generation fully automated terminal with electric automated guided vehicles and remote gantry systems.',
    establishedYear: 2023,
  },
];

export const INITIAL_BERTHS: Berth[] = [
  {
    id: 'b-01',
    code: 'B-01',
    name: 'Quayside Berth 1 (North Deep)',
    terminalId: 'term-1',
    terminalName: 'Pasir Panjang Terminal Phase 1-2',
    lengthMeters: 420,
    depthMeters: 16.5,
    status: 'Occupied',
    currentVesselId: 'v3',
    currentVesselName: 'MV Poseidon Express',
    currentVesselImo: 'IMO 9781234',
    cranesAssigned: ['CR-101', 'CR-102'],
    maxDraftMeters: 15.5,
    lastInspectionDate: '2026-08-14',
  },
  {
    id: 'b-02',
    code: 'B-02',
    name: 'Quayside Berth 2 (Central)',
    terminalId: 'term-1',
    terminalName: 'Pasir Panjang Terminal Phase 1-2',
    lengthMeters: 380,
    depthMeters: 16.0,
    status: 'Occupied',
    currentVesselId: 'v2',
    currentVesselName: 'MV Horizon',
    currentVesselImo: 'IMO 9823412',
    cranesAssigned: ['CR-103'],
    maxDraftMeters: 15.0,
    lastInspectionDate: '2026-07-22',
  },
  {
    id: 'b-03',
    code: 'B-03',
    name: 'Quayside Berth 3 (Reefer Spur)',
    terminalId: 'term-1',
    terminalName: 'Pasir Panjang Terminal Phase 1-2',
    lengthMeters: 350,
    depthMeters: 15.5,
    status: 'Available',
    cranesAssigned: ['CR-104'],
    maxDraftMeters: 14.5,
    lastInspectionDate: '2026-09-01',
  },
  {
    id: 'b-04',
    code: 'B-04',
    name: 'Quayside Berth 4 (Express Berth)',
    terminalId: 'term-1',
    terminalName: 'Pasir Panjang Terminal Phase 1-2',
    lengthMeters: 400,
    depthMeters: 16.5,
    status: 'Occupied',
    currentVesselId: 'v1',
    currentVesselName: 'MV Ocean Star',
    currentVesselImo: 'IMO 9845123',
    cranesAssigned: ['CR-105', 'CR-106'],
    maxDraftMeters: 15.8,
    lastInspectionDate: '2026-08-29',
  },
  {
    id: 'b-05',
    code: 'B-05',
    name: 'Quayside Berth 5 (Feeder East)',
    terminalId: 'term-1',
    terminalName: 'Pasir Panjang Terminal Phase 1-2',
    lengthMeters: 320,
    depthMeters: 14.5,
    status: 'Available',
    cranesAssigned: ['CR-107'],
    maxDraftMeters: 13.5,
    lastInspectionDate: '2026-09-10',
  },
  {
    id: 'b-06',
    code: 'B-06',
    name: 'Keppel Deep Berth Alpha',
    terminalId: 'term-2',
    terminalName: 'Keppel Deepwater Super-Hub',
    lengthMeters: 450,
    depthMeters: 18.5,
    status: 'Occupied',
    currentVesselId: 'v5',
    currentVesselName: 'MV Global Container',
    currentVesselImo: 'IMO 9765431',
    cranesAssigned: ['CR-201', 'CR-202'],
    maxDraftMeters: 17.5,
    lastInspectionDate: '2026-08-05',
  },
  {
    id: 'b-07',
    code: 'B-07',
    name: 'Keppel Deep Berth Bravo',
    terminalId: 'term-2',
    terminalName: 'Keppel Deepwater Super-Hub',
    lengthMeters: 450,
    depthMeters: 19.0,
    status: 'Maintenance',
    cranesAssigned: ['CR-203'],
    maxDraftMeters: 17.8,
    lastInspectionDate: '2026-09-12',
  },
  {
    id: 'b-08',
    code: 'B-08',
    name: 'Keppel Deep Berth Charlie',
    terminalId: 'term-2',
    terminalName: 'Keppel Deepwater Super-Hub',
    lengthMeters: 410,
    depthMeters: 17.5,
    status: 'Occupied',
    currentVesselId: 'v4',
    currentVesselName: 'MV Pacific Dawn',
    currentVesselImo: 'IMO 9812456',
    cranesAssigned: ['CR-204'],
    maxDraftMeters: 16.5,
    lastInspectionDate: '2026-08-19',
  },
  {
    id: 'b-09',
    code: 'B-09',
    name: 'Keppel Deep Berth Delta',
    terminalId: 'term-2',
    terminalName: 'Keppel Deepwater Super-Hub',
    lengthMeters: 360,
    depthMeters: 16.0,
    status: 'Available',
    cranesAssigned: [],
    maxDraftMeters: 15.0,
    lastInspectionDate: '2026-09-02',
  },
  {
    id: 'b-10',
    code: 'B-10',
    name: 'Jurong Bulk Berth 1',
    terminalId: 'term-3',
    terminalName: 'Jurong Island Petrochemical & Bulk Terminal',
    lengthMeters: 340,
    depthMeters: 15.0,
    status: 'Available',
    cranesAssigned: ['CR-301'],
    maxDraftMeters: 14.0,
    lastInspectionDate: '2026-07-30',
  },
  {
    id: 'b-11',
    code: 'B-11',
    name: 'Jurong Liquid Chemical Quay 2',
    terminalId: 'term-3',
    terminalName: 'Jurong Island Petrochemical & Bulk Terminal',
    lengthMeters: 360,
    depthMeters: 15.2,
    status: 'Occupied',
    currentVesselId: 'v6',
    currentVesselName: 'MT Singapore Pioneer',
    currentVesselImo: 'IMO 9642019',
    cranesAssigned: ['CR-302'],
    maxDraftMeters: 14.2,
    lastInspectionDate: '2026-08-11',
  },
  {
    id: 'b-12',
    code: 'B-12',
    name: 'Jurong Heavy Gantry Berth 3',
    terminalId: 'term-3',
    terminalName: 'Jurong Island Petrochemical & Bulk Terminal',
    lengthMeters: 320,
    depthMeters: 14.0,
    status: 'Offline',
    cranesAssigned: [],
    maxDraftMeters: 13.0,
    lastInspectionDate: '2026-09-04',
  },
  {
    id: 'b-13',
    code: 'B-13',
    name: 'Tuas Autonomous Berth 1',
    terminalId: 'term-4',
    terminalName: 'Tuas Mega Automation Terminal (Phase 1)',
    lengthMeters: 440,
    depthMeters: 18.0,
    status: 'Available',
    cranesAssigned: ['CR-401'],
    maxDraftMeters: 17.0,
    lastInspectionDate: '2026-09-08',
  },
  {
    id: 'b-14',
    code: 'B-14',
    name: 'Tuas Autonomous Berth 2',
    terminalId: 'term-4',
    terminalName: 'Tuas Mega Automation Terminal (Phase 1)',
    lengthMeters: 440,
    depthMeters: 18.0,
    status: 'Maintenance',
    cranesAssigned: ['CR-402'],
    maxDraftMeters: 17.0,
    lastInspectionDate: '2026-09-13',
  },
];

export const INITIAL_CRANES: Crane[] = [
  {
    id: 'cr-1',
    code: 'CR-101',
    type: 'STS',
    terminalId: 'term-1',
    terminalName: 'Pasir Panjang Terminal Phase 1-2',
    assignedBerthId: 'b-01',
    assignedBerthCode: 'B-01',
    status: 'Operational',
    efficiencyRating: 4.9,
    lastMaintenanceDate: '2026-08-20',
    nextServiceDate: '2026-10-20',
    movesPerHour: 36,
    manufacturer: 'ZPMC Super Post-Panamax',
  },
  {
    id: 'cr-2',
    code: 'CR-102',
    type: 'STS',
    terminalId: 'term-1',
    terminalName: 'Pasir Panjang Terminal Phase 1-2',
    assignedBerthId: 'b-01',
    assignedBerthCode: 'B-01',
    status: 'Operational',
    efficiencyRating: 4.8,
    lastMaintenanceDate: '2026-08-18',
    nextServiceDate: '2026-10-18',
    movesPerHour: 34,
    manufacturer: 'ZPMC Super Post-Panamax',
  },
  {
    id: 'cr-3',
    code: 'CR-103',
    type: 'STS',
    terminalId: 'term-1',
    terminalName: 'Pasir Panjang Terminal Phase 1-2',
    assignedBerthId: 'b-02',
    assignedBerthCode: 'B-02',
    status: 'Operational',
    efficiencyRating: 4.5,
    lastMaintenanceDate: '2026-07-15',
    nextServiceDate: '2026-09-25',
    movesPerHour: 31,
    manufacturer: 'Liebherr Container Crane',
  },
  {
    id: 'cr-4',
    code: 'CR-104',
    type: 'RTG',
    terminalId: 'term-1',
    terminalName: 'Pasir Panjang Terminal Phase 1-2',
    assignedBerthId: 'b-03',
    assignedBerthCode: 'B-03',
    status: 'Operational',
    efficiencyRating: 4.2,
    lastMaintenanceDate: '2026-08-01',
    nextServiceDate: '2026-11-01',
    movesPerHour: 24,
    manufacturer: 'Konecranes Noell RTG',
  },
  {
    id: 'cr-5',
    code: 'CR-105',
    type: 'STS',
    terminalId: 'term-1',
    terminalName: 'Pasir Panjang Terminal Phase 1-2',
    assignedBerthId: 'b-04',
    assignedBerthCode: 'B-04',
    status: 'Operational',
    efficiencyRating: 5.0,
    lastMaintenanceDate: '2026-08-25',
    nextServiceDate: '2026-11-25',
    movesPerHour: 38,
    manufacturer: 'ZPMC Super Post-Panamax',
  },
  {
    id: 'cr-6',
    code: 'CR-106',
    type: 'STS',
    terminalId: 'term-1',
    terminalName: 'Pasir Panjang Terminal Phase 1-2',
    assignedBerthId: 'b-04',
    assignedBerthCode: 'B-04',
    status: 'Fault',
    efficiencyRating: 2.1,
    lastMaintenanceDate: '2026-06-10',
    nextServiceDate: 'OVERDUE',
    movesPerHour: 12,
    manufacturer: 'ZPMC Super Post-Panamax',
  },
  {
    id: 'cr-7',
    code: 'CR-201',
    type: 'STS',
    terminalId: 'term-2',
    terminalName: 'Keppel Deepwater Super-Hub',
    assignedBerthId: 'b-06',
    assignedBerthCode: 'B-06',
    status: 'Operational',
    efficiencyRating: 4.7,
    lastMaintenanceDate: '2026-08-12',
    nextServiceDate: '2026-10-12',
    movesPerHour: 35,
    manufacturer: 'Mitsui-Paceco Portainer',
  },
  {
    id: 'cr-8',
    code: 'CR-202',
    type: 'STS',
    terminalId: 'term-2',
    terminalName: 'Keppel Deepwater Super-Hub',
    assignedBerthId: 'b-06',
    assignedBerthCode: 'B-06',
    status: 'Operational',
    efficiencyRating: 4.6,
    lastMaintenanceDate: '2026-08-10',
    nextServiceDate: '2026-10-10',
    movesPerHour: 33,
    manufacturer: 'Mitsui-Paceco Portainer',
  },
  {
    id: 'cr-9',
    code: 'CR-203',
    type: 'STS',
    terminalId: 'term-2',
    terminalName: 'Keppel Deepwater Super-Hub',
    assignedBerthId: 'b-07',
    assignedBerthCode: 'B-07',
    status: 'Maintenance',
    efficiencyRating: 3.5,
    lastMaintenanceDate: '2026-09-12',
    nextServiceDate: 'In Progress (Hydraulic Refit)',
    movesPerHour: 0,
    manufacturer: 'Mitsui-Paceco Portainer',
  },
  {
    id: 'cr-10',
    code: 'CR-301',
    type: 'RTG',
    terminalId: 'term-3',
    terminalName: 'Jurong Island Petrochemical & Bulk Terminal',
    assignedBerthId: 'b-10',
    assignedBerthCode: 'B-10',
    status: 'Operational',
    efficiencyRating: 4.0,
    lastMaintenanceDate: '2026-07-28',
    nextServiceDate: '2026-10-28',
    movesPerHour: 22,
    manufacturer: 'Kalmar Heavy Bulk Hoist',
  },
  {
    id: 'cr-11',
    code: 'CR-401',
    type: 'STS',
    terminalId: 'term-4',
    terminalName: 'Tuas Mega Automation Terminal (Phase 1)',
    assignedBerthId: 'b-13',
    assignedBerthCode: 'B-13',
    status: 'Operational',
    efficiencyRating: 5.0,
    lastMaintenanceDate: '2026-09-01',
    nextServiceDate: '2026-12-01',
    movesPerHour: 42,
    manufacturer: 'Tuas Autonomous Dual-Trolley STS',
  },
  {
    id: 'cr-12',
    code: 'CR-402',
    type: 'RTG',
    terminalId: 'term-4',
    terminalName: 'Tuas Mega Automation Terminal (Phase 1)',
    assignedBerthId: 'b-14',
    assignedBerthCode: 'B-14',
    status: 'Maintenance',
    efficiencyRating: 3.8,
    lastMaintenanceDate: '2026-09-13',
    nextServiceDate: 'Sensor Calibration',
    movesPerHour: 0,
    manufacturer: 'Tuas Automated Rail-Mounted Gantry (ARMG)',
  },
];

export const STORAGE_KEYS = {
  TERMINALS: 'docknova_port_terminals_v1',
  BERTHS: 'docknova_port_berths_v1',
  CRANES: 'docknova_port_cranes_v1',
};
