import { ManagedUser } from './types';

export const INITIAL_MOCK_USERS: ManagedUser[] = [
  {
    id: 'usr-1',
    name: 'Capt. Vance Alexander',
    email: 'captain@docknova.com',
    role: 'manager',
    company: 'Tuas Mega Terminal (PSA)',
    status: 'active',
    lastActive: '2 mins ago',
    avatarColor: 'bg-primary/20 text-primary',
    mfaStatus: 'Enforced Hardware Key',
    createdAt: '2026-01-15',
    title: 'Senior Harbor Master & Port Operations Lead',
  },
  {
    id: 'usr-2',
    name: 'Elena Rostova',
    email: 'operator.maersk@docknova.com',
    role: 'user',
    company: 'Maersk Line Maritime',
    status: 'active',
    lastActive: '12 mins ago',
    avatarColor: 'bg-secondary/20 text-secondary',
    mfaStatus: 'Authenticator App',
    createdAt: '2026-02-10',
    title: 'Senior Fleet Dispatcher (Asia-Europe routes)',
  },
  {
    id: 'usr-3',
    name: 'Marcus Drake',
    email: 'admin.ops@docknova.com',
    role: 'admin',
    company: 'DockNova Core Infrastructure',
    status: 'active',
    lastActive: 'Just now',
    avatarColor: 'bg-accent/20 text-accent',
    mfaStatus: 'Enforced Hardware Key',
    createdAt: '2025-11-01',
    title: 'Principal Systems & Kubernetes Administrator',
  },
  {
    id: 'usr-4',
    name: 'Sarah Chen',
    email: 's.chen@cma-cgm.com',
    role: 'user',
    company: 'CMA CGM Shipping',
    status: 'active',
    lastActive: '25 mins ago',
    avatarColor: 'bg-primary/20 text-primary',
    mfaStatus: 'Authenticator App',
    createdAt: '2026-03-04',
    title: 'Carrier Vessel Route Specialist',
  },
  {
    id: 'usr-5',
    name: 'David Tanaka',
    email: 'd.tanaka@one-line.com',
    role: 'user',
    company: 'Ocean Network Express (ONE)',
    status: 'active',
    lastActive: '1 hour ago',
    avatarColor: 'bg-accent/20 text-accent',
    mfaStatus: 'Authenticator App',
    createdAt: '2026-02-28',
    title: 'Operations Coordinator, Southeast Asia',
  },
  {
    id: 'usr-6',
    name: 'Hassan Al-Mansoor',
    email: 'h.mansoor@jurongport.sg',
    role: 'manager',
    company: 'Jurong Port Authority',
    status: 'active',
    lastActive: '2 hours ago',
    avatarColor: 'bg-warning/20 text-warning',
    mfaStatus: 'Enforced Hardware Key',
    createdAt: '2026-01-20',
    title: 'Terminal Berth Allocation Controller',
  },
  {
    id: 'usr-7',
    name: 'Sophie Dubois',
    email: 'sophie.dubois@msc.com',
    role: 'user',
    company: 'Mediterranean Shipping Company (MSC)',
    status: 'pending',
    lastActive: '5 hours ago',
    avatarColor: 'bg-secondary/20 text-secondary',
    mfaStatus: 'None',
    createdAt: '2026-09-12',
    title: 'Fleet Logistics Liaison (Pending Verification)',
  },
  {
    id: 'usr-8',
    name: 'Kenji Sato',
    email: 'k.sato@evergreen-marine.com',
    role: 'user',
    company: 'Evergreen Marine Corp',
    status: 'active',
    lastActive: '1 day ago',
    avatarColor: 'bg-success/20 text-success',
    mfaStatus: 'Authenticator App',
    createdAt: '2026-04-18',
    title: 'Container Vessel Dispatch Supervisor',
  },
  {
    id: 'usr-9',
    name: 'Rachel Sterling',
    email: 'r.sterling@docknova.com',
    role: 'admin',
    company: 'DockNova Security Team',
    status: 'active',
    lastActive: '34 mins ago',
    avatarColor: 'bg-accent/20 text-accent',
    mfaStatus: 'Enforced Hardware Key',
    createdAt: '2025-12-10',
    title: 'Information Security & Compliance Officer',
  },
  {
    id: 'usr-10',
    name: 'Mateo Morales',
    email: 'm.morales@hapag-lloyd.com',
    role: 'user',
    company: 'Hapag-Lloyd AG',
    status: 'inactive',
    lastActive: '14 days ago',
    avatarColor: 'bg-surface-3 text-text-muted',
    mfaStatus: 'SMS Verify',
    createdAt: '2026-01-08',
    title: 'Voyage Planner (Account Deactivated)',
  },
  {
    id: 'usr-11',
    name: 'Lin Wei Ming',
    email: 'weiming.lin@psa.sg',
    role: 'manager',
    company: 'PSA Pasir Panjang Terminal',
    status: 'active',
    lastActive: '45 mins ago',
    avatarColor: 'bg-warning/20 text-warning',
    mfaStatus: 'Enforced Hardware Key',
    createdAt: '2026-02-01',
    title: 'Crane Operations & Yard Master',
  },
  {
    id: 'usr-12',
    name: 'Chloe Bennett',
    email: 'c.bennett@cosco-shipping.com',
    role: 'user',
    company: 'COSCO Shipping Lines',
    status: 'pending',
    lastActive: '2 days ago',
    avatarColor: 'bg-secondary/20 text-secondary',
    mfaStatus: 'None',
    createdAt: '2026-09-13',
    title: 'Pacific Trade Carrier Analyst (Pending Onboarding)',
  },
  {
    id: 'usr-13',
    name: 'Aiden Pearce',
    email: 'a.pearce@docknova.com',
    role: 'admin',
    company: 'DockNova Systems Support',
    status: 'active',
    lastActive: '3 hours ago',
    avatarColor: 'bg-accent/20 text-accent',
    mfaStatus: 'Authenticator App',
    createdAt: '2026-03-15',
    title: 'DevOps & Telemetry Pipeline Specialist',
  },
  {
    id: 'usr-14',
    name: 'Amara Okafor',
    email: 'a.okafor@pacific-carriers.com',
    role: 'user',
    company: 'Pacific International Lines (PIL)',
    status: 'inactive',
    lastActive: '3 weeks ago',
    avatarColor: 'bg-surface-3 text-text-muted',
    mfaStatus: 'SMS Verify',
    createdAt: '2026-01-19',
    title: 'Feeder Operations Planner (Dormant)',
  },
];
